version: "3.4"

services:
  db:
    image: postgres:12
    restart: always
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

  query-node:
    restart: unless-stopped
    build:
      context: .
      target: query-node
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - WARTHOG_DB_HOST=db
    ports:
      - "8080:${GRAPHQL_SERVER_PORT}"
    depends_on:
      - db

  processor:
    restart: unless-stopped
    build:
      context: .
      target: processor
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - WARTHOG_DB_HOST=db
      - POLL_INTERVAL_MS=300
      - TYPEORM_HOST=db
      - DEBUG=hydra-processor:*
    command: sh -c "yarn db:create && yarn workspace query-node db:sync && yarn db:migrate && yarn processor:start"
